# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"now": "00_core.ipynb",
         "get_dict_subset": "00_core.ipynb",
         "FaceLandmarks": "00_core.ipynb",
         "VisemeConfig": "00_core.ipynb",
         "LogFile": "00_core.ipynb",
         "viseme_dataset_from_capture_sessions": "05a_ml_data.ipynb",
         "VisemeDatasetHelper": "05a_ml_data.ipynb",
         "save_state_dict": "05b_ml_model.ipynb",
         "load_state_dict": "05b_ml_model.ipynb",
         "get_class_count": "05b_ml_model.ipynb",
         "create_confusion_matrix": "05b_ml_model.ipynb",
         "plot_confusion_matrix": "05b_ml_model.ipynb",
         "get_idxs_of_interest": "05b_ml_model.ipynb"}

modules = ["core.py",
           "ml/data.py",
           "ml/model.py"]

doc_url = "https://pete88b.github.io/expoco/"

git_url = "https://github.com/pete88b/expoco/tree/main/"

def custom_doc_links(name): return None
