# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ScreenABC": "10_screen.ipynb",
         "to_screen_zone": "10_screen.ipynb",
         "new_windows_screen": "10_screen.ipynb",
         "PointerABC": "20_pointer.ipynb",
         "new_windows_pointer": "20_pointer.ipynb",
         "KeyboardABC": "30_keyboard.ipynb",
         "new_windows_keyboard": "30_keyboard.ipynb",
         "video_capture_session": "40_video.ipynb"}

modules = ["screen.py",
           "pointer.py",
           "keyboard.py",
           "video.py"]

doc_url = "https://pete88b.github.io/expoco/"

git_url = "https://github.com/pete88b/expoco/tree/main/"

def custom_doc_links(name): return None
