# AUTOGENERATED! DO NOT EDIT! File to edit: 10_screen.ipynb (unless otherwise specified).

__all__ = ['ScreenABC', 'to_screen_zone', 'new_windows_screen']

# Cell
from abc import ABC,abstractmethod

# Cell
class ScreenABC(ABC):
    @abstractmethod
    def get_screen_size(self):
        "Return the `size` of the screen: [screen_width, screen_height]"

# Cell
def to_screen_zone(screen_size, point):
    "Return the zone of a `point` within a screen"
    #TODO: we're assuming screen is landscape
    screen_center = [i//2 for i in screen_size]
    distances = [abs(a-b) for a,b in zip(point,screen_center)]
    distances[0] = distances[0] // (screen_size[0] // screen_size[1])
    return distances[0] if distances[0] > distances[1] else distances[1]

# Cell
def new_windows_screen():
    import win32api
    class WindowsScreen(ScreenABC):
        def get_screen_size(self):
            return win32api.GetSystemMetrics(0), win32api.GetSystemMetrics(1)
    return WindowsScreen()