# AUTOGENERATED! DO NOT EDIT! File to edit: 11d_viseme_image_model.ipynb (unless otherwise specified).

__all__ = ['prepare_for_inference']

# Cell
from .data import *
import numpy as np
import cv2

# Cell
def prepare_for_inference(image, crop=True):
    "Convert a cv2 style image to something that can be used as input to a CNN"
    if crop:
        image = ImageHelper().face_crop(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = np.transpose(image, (2, 0, 1))
    image = (image/255.)
    image = image.astype(np.float32)
    return image